### PR TITLE
G-Mode Bottom of Vertical Doors - Maridia

### PR DESCRIPTION
**Pull request by kjbranch**

### CODE REVIEW

**Review by osse101 — COMMENTED** [review]
GravityJump with bombs with enough momentum to reach the door is closer to insane than extreme when using power bombs.

**Comment by kjbranch** [comment]
the bomb method is quite precise. I dont think itll work with a PB because of not being able to use pause when a PB has been laid.

**Comment by osse101** [comment]
I thought I remembered trying it with PBs, but it does look pretty impossible.
Without it the bomb gravity jump is mostly pointless.  Want to take them out?

**Comment by kjbranch** [comment]
Oh, didnt think of that. I'll remove them

**Pull request merged**
